services:
  postgres:
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25-alpine
    ports:
      - ${NGINX_PORT}:80
    env_file:
      - .env
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d
      - ./nfl_client_data:/www/nfl_client_data